networks:
  notesnet:

# container_name(if not defined explicitly) === service name by default
services:
  caddy:
    image: caddy:latest
    networks:
      - notesnet
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${PWD}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/caddy/data:/data
    restart: unless-stopped
    profiles:
      - allinone

  notes-backend:
    image: sti80/notes-backend:0.0.6-alpha
    networks:
      - notesnet
    environment:
      MYID_URL: http://notes-id:3001/.well-known/jwks.json
      MONGO_URL: mongodb+srv://Stipaxa:dAhDIyylpU2j0TxLGvBi@homyak.quto1.mongodb.net/?retryWrites=true&w=majority
      CORS_ALLOWED_ORIGINS: http://notes.secoority.lol:8080
    ports:
      - 3000:3000
    restart: unless-stopped
    profiles:
      - allinone
      - aws

  notes-id:
    image: sti80/notes-id:0.0.6-alpha
    networks:
      - notesnet
    environment:
      MONGO_URL: mongodb+srv://Stipaxa:dAhDIyylpU2j0TxLGvBi@homyak.quto1.mongodb.net/?retryWrites=true&w=majority
      CORS_ALLOWED_ORIGINS: http://notes.secoority.lol:8080
      KEY_LENGTH: 2048
      KEY_ROTATION_SCHEDULE: '0 0 1 * *'
      ACCESS_TOKEN_EXPIRES_IN: 45m
      REFRESH_TOKEN_EXPIRES_IN: 15d
      PASSWORD_HASH_SALT: 'super_secret'
    ports:
      - 3001:3001
    restart: unless-stopped
    profiles:
      - allinone
      - aws

  notes-ui:
    image: sti80/notes-ui:0.0.6-alpha
    networks:
      - notesnet
    environment:
      VITE_BASE_ID_URL: 'https://notes.secoority.lol'
      VITE_BASE_BE_URL: 'https://notes.secoority.lol'
    ports:
      - 8080:8080
    restart: no
    profiles:
      - allinone
