networks:
  notesnet:

services:
  notes-backend:
    image: sti80/notes-backend:0.0.5-alpha
    networks:
      - notesnet
    environment:
      MYID_URL: http://notes-id:3001/.well-known/jwks.json
      MONGO_URL: mongodb+srv://Stipaxa:dAhDIyylpU2j0TxLGvBi@homyak.quto1.mongodb.net/?retryWrites=true&w=majority
      CORS_ALLOWED_ORIGINS: https://notes.tayadev.com
    ports:
      - 3000:3000
    restart: unless-stopped

  notes-id:
    image: sti80/notes-id:0.0.5-alpha
    networks:
      - notesnet
    environment:
      MONGO_URL: mongodb+srv://Stipaxa:dAhDIyylpU2j0TxLGvBi@homyak.quto1.mongodb.net/?retryWrites=true&w=majority
      CORS_ALLOWED_ORIGINS: https://notes.tayadev.com
      KEY_LENGTH: 2048
      KEY_ROTATION_SCHEDULE: '0 0 1 * *'
      ACCESS_TOKEN_EXPIRES_IN: 45m
      REFRESH_TOKEN_EXPIRES_IN: 15d
    ports:
      - 3001:3001
    restart: unless-stopped
